allow_remote_control yes
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+h launch --cwd=current --location=hsplit
#map ctrl+shift+v launch --cwd=current --location=vsplit
enabled_layouts stack,vertical
